/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SkataImport } from './routes/skata'

// Create/Update Routes

const SkataRoute = SkataImport.update({
  id: '/skata',
  path: '/skata',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skata': {
      id: '/skata'
      path: '/skata'
      fullPath: '/skata'
      preLoaderRoute: typeof SkataImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/skata': typeof SkataRoute
}

export interface FileRoutesByTo {
  '/skata': typeof SkataRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/skata': typeof SkataRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/skata'
  fileRoutesByTo: FileRoutesByTo
  to: '/skata'
  id: '__root__' | '/skata'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SkataRoute: typeof SkataRoute
}

const rootRouteChildren: RootRouteChildren = {
  SkataRoute: SkataRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/skata"
      ]
    },
    "/skata": {
      "filePath": "skata.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
